### ISSUE TITLE
add code of conduct 

### ISSUE THREAD

**Issue by HappyGoFishing** [ThatOneCalculator/systemd-yodad#1]
![image](https://github.com/ThatOneCalculator/systemd-yodad/assets/85656267/e929198f-afee-4ba5-b51e-d72b79f2244a)

make drew happy 😊

**Comment by ThatOneCalculator** [comment]
code of conduct: yoda

**Comment by ThatOneCalculator** [comment]
https://github.com/ThatOneCalculator/systemd-yodad/blob/main/CODE_OF_CONDUCT.md
